#!/bin/sh

export RESTIC_TEST_FUSE=0
export RESTIC_TEST_CLOUD_BACKENDS=0

go test $(go list ./...|grep -E -v "examples|cmd")

echo
echo "Running integration tests..."
echo

export PATH=./integration/vendor:./integration/vendor/bats/bin:$PATH
./script/init-test-repo > /dev/null
. ./examples/creds

if [ "$(uname)" = "Linux" ]; then
  bats -r integration
fi
