#!/bin/bash
#
# Script to sync with restic's upstream source
#
set -e

RESTIC_SOURCE=$HOME/git/restic/restic

fix_paths() {
  gomove -d "$1" github.com/restic/restic github.com/rubiojr/rapi
  gomove -d "$1" github.com/rubiojr/rapi/internal/crypto github.com/rubiojr/rapi/crypto
  gomove -d "$1" github.com/rubiojr/rapi/internal/repository github.com/rubiojr/rapi/repository 
  gomove -d "$1" github.com/rubiojr/rapi/internal/restic github.com/rubiojr/rapi/restic
  gomove -d "$1" github.com/rubiojr/rapi/internal/backend github.com/rubiojr/rapi/backend
  gomove -d "$1" github.com/rubiojr/rapi/internal/pack github.com/rubiojr/rapi/pack
}

# Sync rapi's public modules
for dir in restic crypto repository pack backend; do
  rsync -a $RESTIC_SOURCE/internal/$dir/ $dir/
  fix_paths $dir 
done


# Sync the rest of the modules
rsync -a $RESTIC_SOURCE/internal/ internal/
# These where made public
rm -rf internal/restic
rm -rf internal/pack
rm -rf internal/backend
rm -rf internal/crypto
rm -rf internal/repository
fix_paths internal
