name: ci
on: [push]
jobs:
  cibuild:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15.x
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Test
      run: make test
